const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/index'))
  .get('/native.ejs',(req,res) => res.render('pages/native.ejs'))
  .get('/land.ejs',(req,res) => res.render('pages/land.ejs'))
  .get('/grant1.ejs',(req,res) => res.render('pages/grant1.ejs'))
  .get('/grant2.ejs',(req,res) => res.render('pages/grant2.ejs'))
  .get('/grant3.ejs',(req,res) => res.render('pages/grant3.ejs'))
  .get('/grant4.ejs',(req,res) => res.render('pages/grant4.ejs'))
  .get('/grant5.ejs',(req,res) => res.render('pages/grant5.ejs'))
  .get('/grant6.ejs',(req,res) => res.render('pages/grant6.ejs'))
  .get('/grant7.ejs',(req,res) => res.render('pages/grant7.ejs'))
  .get('/grant8.ejs',(req,res) => res.render('pages/grant8.ejs'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
